import { projectType } from "@/lib/types"

const projects : projectType[] = [
    {
        id: 0,
        url: 'https://useinspirely.vercel.app',
        slug: 'inspirely-pwa',
        title: 'Inspirely',
        description: 'A modern blogging and content discovery platform for writers and readers.',
        overview: 'Inspirely is a content creation and sharing platform that enables writers and creators to publish, discover, and connect through meaningful storytelling. It provides a rich writing experience with community features like following, trending topics, notifications, and search functionality.',
        images: [
            "/inspirely-thumbnail.png",
            "/inspirely-2.png",
            "/inspirely-3.png",
            "/inspirely-4.png",
            "/inspirely-5.png",
            "/inspirely-6.png",
            "/inspirely-7.png",
        ],
        expertise: 'Full Stack',
        techStack: 'Next.js 16, React 19, TypeScript, TailwindCSS 4, Radix UI, TipTap (rich text editor), React Query, React Hook Form, Zod, Lucide Icons, Sonner (toasts)',
        year: '2026'
    },
    {
        id: 1,
        url: 'https://useshoppe.vercel.app/',
        slug: 'shoppe-pwa',
        title: 'Shoppe',
        description: 'Shopee is a full-stack e-commerce marketplace built with Next.js, featuring product catalogs, chat, payments, and seller dashboards.',
        overview: 'Shopee is a full-featured e-commerce marketplace platform with product browsing by categories/subcategories, user profiles, orders/sales management, chat/inbox, payments (cards/banks via Paystack), search (Algolia), notifications, and settings. Supports buying/selling, product management, real-time chat via Socket.io, and Firebase integration.',
        images: [
            "/shoppe-1.png",
            "/shoppe-2.png",
            "/shoppe-3.png",
            "/shoppe-4.png",
            "/shoppe-5.png",
            "/shoppe-6.png",
            "/shoppe-7.png"
        ],
        expertise: 'Full Stack',
        techStack: 'Next.js 15 (App Router), TailwindCSS 4, Shadcn UI (with Radix UI, class-variance-authority), TypeScript, GSAP + Framer Motion, TanStack Query, React Hook Form + Zod, Firebase, Mastra, Express.js (server), BullMQ/Redis (queues), Socket.io, Algolia, Paystack, Next Cloudinary, React Email/Resend, Lucide icons',
        year: '2025'
    },
    {
        id: 2,
        url: 'https://swirlblog.vercel.app',
        slug: 'swirl',
        title: 'Swirl',
        description: ' AI-powered technology news and learning platform.',
        overview: 'Swirl is an AI-powered technology news and learning platform that serves as a comprehensive hub for exploring Artificial Intelligence innovations, featuring a vast collection of articles, research blogs, ebooks, and resources dedicated to future technologies.',
        images: [
            "/project-1.png",
            "/swirl-2.png",
            "/swirl-3.png",
            "/swirl-4.png",
            "/swirl-5.png",
            "/swirl-6.png",
            "/swirl-7.png",
        ],
         expertise: 'Full Stack',
        techStack: 'React, Vite, TailwindCSS, TypeScript, Supabase, React Router, React Hook Form, TanStack React Query, React Toastify',
        year: '2024'
    },
    {
        id: 3,
        url: 'https://briefly-web-app.vercel.app',
        slug: 'briefly-pwa',
        title: "Briefly",
        description: 'AI Powered webpage bookmarker extension.',
        overview: "Briefly is a Chrome extension that intelligently bookmarks webpages by generating AI-powered summaries. Users can save pages they're browsing with automatic title extraction and content summarization, then access all their bookmarks through the extension's popup interface with Google authentication.",
        images: [
            "/briefly-1.jpg",
            "/briefly-2.jpg",
            "/briefly-3.jpg",
            "/briefly-3.jpg",
            "/briefly-3.jpg",
            "/briefly-2.jpg",
            "/briefly-1.jpg",
        ],
        expertise: 'Front-End (Chrome Extension Development)',
        techStack: 'JavaScript (Vanilla), HTML, CSS, Chrome Extensions API, Firebase Authentication, Google OAuth 2.0, Render (Backend hosting)',
        year: '2025'
    },    
    {
        id: 4,
        url: 'https://pay4me-alpha.vercel.app/',
        slug: 'pay4me',
        title: 'Pay4Me',
        description: 'A modern web application simplifying cross-border payments for international students.',
        overview: 'Pay4Me is a modern web application simplifying cross-border payments for international students, enabling fast tuition, school fees, SEVIS, WES, visa applications, and more to universities, businesses, and agencies.',
        images: [
            "/pay4me-8.png",
            "/pay4me-1.png",
            "/pay4me-3.png",
            "/pay4me-4.png",
            "/pay4me-5.png",
            "/pay4me-6.png",
            "/pay4me-7.png",
        ],
        expertise: 'Front-end',
        techStack: 'Vite, React, TypeScript, TailwindCSS, GSAP, Swiper, React Icons',
        year: '2025'
    },
    {
        id: 5,
        url: 'https://zentryx.vercel.app/',
        slug: 'zentry',
        title: 'Zentry',
        description: 'A modern, animated landing page for Zentry, a gaming platform.',
        overview: 'Zentry Clone is a modern, animated landing page for Zentry, a gaming platform that redefines gaming identity, reality, and agentic AI through the Meta Game Layer and Play Economy.',
        images: [
            "/zentry-1.png",
            "/zentry-2.png",
            "/zentry-3.png",
            "/zentry-4.png",
            "/zentry-5.png",
            "/zentry-6.png",
            "/zentry-7.png",
        ],
         expertise: 'Front-end',
        techStack: 'Vite, React, TypeScript, TailwindCSS, GSAP, react-use, react-icons',
        year: '2025'
    },
    {
        id: 6,
        url: 'https://dart-agro-system.vercel.app/',
        slug: 'dart-agro-system',
        title: 'Dart Agro System',
        description: 'A modern web platform showcasing advanced agricultural technology and machinery solutions for global farming operations.',
        overview: 'Dart Agro System is a global manufacturer of heavy agricultural machinery and smart farming technology with operations across 40+ countries, empowering farmers and agribusinesses worldwide with intelligent machinery, precision systems, and sustainable engineering solutions.',
        images: [
            "/das-1.png",
            "/das-2.png",
            "/das-3.png",
            "/das-4.png",
            "/das-5.png",
            "/das-6.png",
            "/das-7.png",
        ],
         expertise: 'Front-end',
        techStack: 'Next.js, React, TypeScript, TailwindCSS, ShadCN UI, GSAP, Zustand, Lucide Icons, Embla Carousel',
        year: '2025'
    },
    {
        id: 7,
        url: 'https://velvet-pour-phi.vercel.app/',
        slug: 'velvet',
        title: 'Velvet',
        description: 'A premium cocktail bar website showcasing an elegant collection of craft cocktails and premium beverages.',
        overview: 'Velvet is a premium cocktail bar website showcasing an elegant collection of craft cocktails and premium beverages. The platform features interactive menu browsing, cocktail showcases, customer testimonials, and location/contact information for a sophisticated drinking establishment.',
        images: [
            "/velvet-1.png",
            "/velvet-2.png",
            "/velvet-3.png",
            "/velvet-4.png",
            "/velvet-5.png",
            "/velvet-6.png",
            "/velvet-7.png",
        ],
         expertise: 'Front-End',
        techStack: 'React, Vite, TailwindCSS, GSAP (GreenSock Animation Platform), JavaScript',
        year: '2025'
    },
    {
        id: 8,
        url: 'https://apple-fifteen-pro.vercel.app/',
        slug: 'apple-website',
        title: 'Apple Website',
        description: 'A premium Apple iPhone 15 Pro product showcase website featuring interactive 3D models, immersive animations, and dynamic video highlights.',
        overview: 'A premium Apple iPhone 15 Pro product showcase website featuring interactive 3D models, immersive animations, and dynamic video highlights. The platform demonstrates cutting-edge UI/UX design with seamless navigation through product features including the A17 Pro chip, titanium construction, advanced camera system, and the innovative Action button.',
        images: [
            "/apple-1.png",
            "/apple-2.png",
            "/apple-3.png",
            "/apple-4.png",
            "/apple-5.png",
            "/apple-6.png",
            "/apple-7.png",
        ],
         expertise: 'Front-End',
        techStack: 'React, Vite, TailwindCSS, GSAP, Three.js, React Three Fiber, Swiper, React Icons',
        year: '2025'
    },
    {
        id: 9,
        url: 'https://pix-splash.vercel.app/',
        slug: 'pixsplash',
        title: 'PixSplash',
        description: 'a free stock photos website where users can browse, save images to collections, add favorites, download images, and share collections',
        overview: 'PixSplash is a free stock photos website where users can browse, save images to collections, add favorites, download images, and share collections. Built with Next.js, TailwindCSS, Headless UI, and MongoDB.',
        images: [
            "/pixsplash-1.png",
            "/pixsplash-2.png",
            "/pixsplash-3.png",
            "/pixsplash-4.png",
            "/pixsplash-5.png",
            "/pixsplash-1.png",
            "/pixsplash-2.png",
        ],
         expertise: 'Full Stack',
        techStack: 'Next.js 13, React 18, TailwindCSS, Headless UI, Redux Toolkit, Framer Motion, MongoDB, Mongoose, NextAuth, React Hook Form, React Hot Toast, React Icons, React Masonry CSS',
        year: '2023'
    }
]

export default projects